# Generated by Django 4.2.4 on 2023-08-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="postType",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(to="news.category"),
        ),
    ]
